### ISSUE TITLE
Error parsing Teams leveldb

### ISSUE THREAD

**Issue by kazumamog** [lxndrblz/forensicsim#11]
Hi, Im having error parsing Teams leveldb.
The scripts returns error says like this;

`(base) C:\Users\User\Desktop\forensicsim-0.5.0\utils>python main.py -f ..\..\foren\AppData\local\Packages\MicrosoftTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\EBWebView\Default\IndexedDB\https_teams.live.com_0.indexeddb.leveldb -o ..\test.json
 _____                        _            _
|  ___|__  _ __ ___ _ __  ___(_) ___ ___  (_)_ __ ___
| |_ / _ \| '__/ _ \ '_ \/ __| |/ __/ __| | | '_ ` _ \
|  _| (_) | | |  __/ | | \__ \ | (__\__ \_| | | | | | |
|_|  \___/|_|  \___|_| |_|___/_|\___|___(_)_|_| |_| |_|

__  ___                  _     _____           _
\ \/ / |_ _ __ __ _  ___| |_  |_   _|__   ___ | |
 \  /| __| '__/ _` |/ __| __|   | |/ _ \ / _ \| |
 /  \| |_| | | (_| | (__| |_    | | (_) | (_) | |
/_/\_\\__|_|  \__,_|\___|\__|   |_|\___/ \___/|_|

Traceback (most recent call last):
  File "C:\Users\User\Desktop\forensicsim-0.5.0\utils\main.py", line 314, in <module>
    cli()
  File "C:\Users\User\Desktop\forensicsim-0.5.0\utils\main.py", line 309, in cli
    run(args)
  File "C:\Users\User\Desktop\forensicsim-0.5.0\utils\main.py", line 292, in run
    process_db(args.filepath, args.outputpath)
  File "C:\Users\User\Desktop\forensicsim-0.5.0\utils\main.py", line 282, in process_db
    extracted_values = shared.parse_db(filepath)
  File "C:\Users\User\Desktop\forensicsim-0.5.0\utils\shared.py", line 170, in parse_db
    db = FastIndexedDB(filepath)
  File "C:\Users\User\Desktop\forensicsim-0.5.0\utils\shared.py", line 53, in __init__
    self.fetch_data()
  File "C:\Users\User\Desktop\forensicsim-0.5.0\utils\shared.py", line 77, in fetch_data
    if db_id.dbid_no > 0x7f:
TypeError: '>' not supported between instances of 'NoneType' and 'int'`

Dumping localstorage works file but with leveldb not working for me.
could you help plz..

**Comment by kazumamog** [comment]
I figured it out.  There is "None" in db_id.dbid_no. 
This is awesome tool by the way.
thx!

**Comment by KarelZe** [comment]
Glad to hear. You're welcome.
