### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by mboufahja** [lxndrblz/forensicsim#19]
Hi,
The code is perfectly working with the classic Teams. When I switch to new teams, I get the following error:

```text
 _____                        _            _
|  ___|__  _ __ ___ _ __  ___(_) ___ ___  (_)_ __ ___
| |_ / _ \| '__/ _ \ '_ \/ __| |/ __/ __| | | '_ ` _ \
|  _| (_) | | |  __/ | | \__ \ | (__\__ \_| | | | | | |
|_|  \___/|_|  \___|_| |_|___/_|\___|___(_)_|_| |_| |_|

__  ___                  _     _____           _
\ \/ / |_ _ __ __ _  ___| |_  |_   _|__   ___ | |
 \  /| __| '__/ _` |/ __| __|   | |/ _ \ / _ \| |
 /  \| |_| | | (_| | (__| |_    | | (_) | (_) | |
/_/\_\\__|_|  \__,_|\___|\__|   |_|\___/ \___/|_|


WARNING: Skipping database Teams:app-definition-images-manager:d826664f-15b5-465e-b789-65c3c61e69ee:e72c2f67-db47-49f8-9dfc-dd1bbfe072c3
WARNING: Skipping database Teams:app-device-permissions-manager:d826664f-15b5-465e-b789-65c3c61e69ee:e72c2f67-db47-49f8-9dfc-dd1bbfe072c3
WARNING: Skipping database Teams:apps-usage-manager:d826664f-15b5-465e-b789-65c3c61e69ee:e72c2f67-db47-49f8-9dfc-dd1bbfe072c3
WARNING: Skipping database Teams:artifacts-manager:d826664f-15b5-465e-b789-65c3c61e69ee:e72c2f67-db47-49f8-9dfc-dd1bbfe072c3
WARNING: Skipping database Teams:channel-installed-apps-manager:d826664f-15b5-465e-b789-65c3c61e69ee:e72c2f67-db47-49f8-9dfc-dd1bbfe072c3
WARNING: Skipping database Teams:cross-tenant-policies-manager:d826664f-15b5-465e-b789-65c3c61e69ee:e72c2f67-db47-49f8-9dfc-dd1bbfe072c3
WARNING: Skipping database Teams:extracted_app_definition-manager:d826664f-15b5-465e-b789-65c3c61e69ee:e72c2f67-db47-49f8-9dfc-dd1bbfe072c3
WARNING: Skipping database Teams:files-thumbnail-blob-content-manager:d826664f-15b5-465e-b789-65c3c61e69ee:e72c2f67-db47-49f8-9dfc-dd1bbfe072c3
WARNING: Skipping database Teams:mentions-manager:d826664f-15b5-465e-b789-65c3c61e69ee:8:orgid:e72c2f67-db47-49f8-9dfc-dd1bbfe072c3
WARNING: Skipping database Teams:platform-store-manager:d826664f-15b5-465e-b789-65c3c61e69ee:e72c2f67-db47-49f8-9dfc-dd1bbfe072c3
WARNING: Skipping database Teams:recommendedteams:d826664f-15b5-465e-b789-65c3c61e69ee:e72c2f67-db47-49f8-9dfc-dd1bbfe072c3
WARNING: Skipping database Teams:replychain-metadata-manager:d826664f-15b5-465e-b789-65c3c61e69ee:e72c2f67-db47-49f8-9dfc-dd1bbfe072c3
WARNING: Skipping database Teams:store-device-manager:d826664f-15b5-465e-b789-65c3c61e69ee:e72c2f67-db47-49f8-9dfc-dd1bbfe072c3
Traceback (most recent call last):
  File "main.py", line 314, in <module>
  File "main.py", line 309, in cli
  File "main.py", line 292, in run
  File "main.py", line 282, in process_db
  File "shared.py", line 179, in parse_db
  File "shared.py", line 131, in iterate_records
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
[21520] Failed to execute script 'main' due to unhandled exception!

```

You will find attached an example of a leveldb database containing new teams data, so you can duplicate the issue.
Any help would be appreciated.
[https_teams.microsoft.com_0.indexeddb.leveldb.zip](https://github.com/lxndrblz/forensicsim/files/12536033/https_teams.microsoft.com_0.indexeddb.leveldb.zip)
![New_teams](https://github.com/lxndrblz/forensicsim/assets/101709598/6fd00c34-6b89-401f-a4b6-dcf087cc7cb7)

**Comment by lxndrblz** [comment]
@mboufahja  Would you mind sharing the version that you are on?

I have just run a little test and was able to reproduce the error.

Changing this line:
[            if None == global_id.dbid_no:](https://github.com/lxndrblz/forensicsim/blob/6b165d690df6720a9470af4221a26830b50607bd/utils/shared.py#L127C42-L127C42)


To this:

```python
            if global_id.dbid_no == None or self.database_metadata.get_meta(global_id.dbid_no,
                                                                            DatabaseMetadataType.MaximumObjectStoreId) == None:
```

Has worked for me. Would you mind running it on your test data please?

**Comment by mboufahja** [comment]
Thank you @lxndrblz for your help. 
When I try the solution you mentioned, I do no more get an error, but I get an empty array in the created Json file.
If, I have the old teams at the beginnig, then I switch to the new Teams, the created Json file will contain only the messaged related to the old version of teams.

This is new Teams version I'm using:
![image](https://github.com/lxndrblz/forensicsim/assets/101709598/ffff7b2c-62a2-44e4-bbfc-57156ab574bb)

Thank you so much for your time and the great work you are doing.
