### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by Beercow** [lxndrblz/forensicsim#88]
Receiving the following error with Teams version 49/24053101421.

buddylist skypexspaces-contacts-020546b9-ddfd-459b-89d1-12a53f27a5e2-75d91126-0e24-471a-99e1-36ce3b8dd809 (Records: 0)
replychains skypexspaces-020546b9-ddfd-459b-89d1-12a53f27a5e2-75d91126-0e24-471a-99e1-36ce3b8dd809 (Records: 0)
conversations skypexspaces-020546b9-ddfd-459b-89d1-12a53f27a5e2-75d91126-0e24-471a-99e1-36ce3b8dd809 (Records: 0)
people skypexspaces-020546b9-ddfd-459b-89d1-12a53f27a5e2-75d91126-0e24-471a-99e1-36ce3b8dd809 (Records: 0)
people Teams:substrate-suggestions-manager:75d91126-0e24-471a-99e1-36ce3b8dd809:020546b9-ddfd-459b-89d1-12a53f27a5e2 (Records: 0)
Traceback (most recent call last):
  File "main.py", line 65, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "main.py", line 61, in process_cmd
  File "forensicsim\parser.py", line 380, in process_db
  File "forensicsim\backend.py", line 157, in parse_db
  File "ccl_chromium_reader\ccl_chromium_indexeddb.py", line 821, in iterate_records
  File "forensicsim\backend.py", line 75, in custom_iterate_records
TypeError: IndexedDbRecord.__init__() missing 1 required positional argument: 'origin_file'
[42272] Failed to execute script 'main' due to unhandled exception!

**Comment by lxndrblz** [comment]
Thanks for reporting the issue. I think it's related to a recent change. I already have an idea how this could be resolved.
