### ISSUE TITLE
TypeError: IndexedDbRecord.__init__() missing 1 required positional argument: 'origin_file'

### ISSUE THREAD

**Issue by kenichi-kobayashi** [lxndrblz/forensicsim#92]
The following error occurs.

Microsoft Teams Version : 24152.415.2975.367 

Prompt>ms_teams_parser.exe -f [indexeddb.leveldb] -o test.txt
 _____                        _            _
|  ___|__  _ __ ___ _ __  ___(_) ___ ___  (_)_ __ ___
| |_ / _ \| '__/ _ \ '_ \/ __| |/ __/ __| | | '_ ` _ \
|  _| (_) | | |  __/ | | \__ \ | (__\__ \_| | | | | | |
|_|  \___/|_|  \___|_| |_|___/_|\___|___(_)_|_| |_| |_|
__  ___                  _     _____           _
\ \/ / |_ _ __ __ _  ___| |_  |_   _|__   ___ | |
 \  /| __| '__/ _` |/ __| __|   | |/ _ \ / _ \| |
 /  \| |_| | | (_| | (__| |_    | | (_) | (_) | |
/_/\_\\__|_|  \__,_|\___|\__|   |_|\___/ \___/|_|

people Teams:substrate-suggestions-manager:react-web-client:98bbbf0a-f92e-49d3-9743-7205b1e5b31f:8c433003-a081-4dfb-a631-100526250b1a:ja-jp (Records: 0)
Traceback (most recent call last):
  File "main.py", line 65, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "main.py", line 61, in process_cmd
  File "forensicsim\parser.py", line 380, in process_db
  File "forensicsim\backend.py", line 157, in parse_db
  File "ccl_chromium_reader\ccl_chromium_indexeddb.py", line 821, in iterate_records
  File "forensicsim\backend.py", line 90, in custom_iterate_records
  File "ccl_chromium_reader\ccl_chromium_indexeddb.py", line 566, in read_record_precursor
  File "ccl_chromium_reader\ccl_chromium_indexeddb.py", line 658, in get_blob
ValueError: Can't resolve blob if blob dir is not set
[12540] Failed to execute script 'main' due to unhandled exception!

Prompt>ms_teams_parser.exe -f [indexeddb.leveldb] -b [indexeddb.blob] -o test.txt

 _____                        _            _
|  ___|__  _ __ ___ _ __  ___(_) ___ ___  (_)_ __ ___
| |_ / _ \| '__/ _ \ '_ \/ __| |/ __/ __| | | '_ ` _ \
|  _| (_) | | |  __/ | | \__ \ | (__\__ \_| | | | | | |
|_|  \___/|_|  \___|_| |_|___/_|\___|___(_)_|_| |_| |_|
__  ___                  _     _____           _
\ \/ / |_ _ __ __ _  ___| |_  |_   _|__   ___ | |
 \  /| __| '__/ _` |/ __| __|   | |/ _ \ / _ \| |
 /  \| |_| | | (_| | (__| |_    | | (_) | (_) | |
/_/\_\\__|_|  \__,_|\___|\__|   |_|\___/ \___/|_|

people Teams:substrate-suggestions-manager:react-web-client:98bbbf0a-f92e-49d3-9743-7205b1e5b31f:8c433003-a081-4dfb-a631-100526250b1a:ja-jp (Records: 0)
Traceback (most recent call last):
  File "main.py", line 65, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "main.py", line 61, in process_cmd
  File "forensicsim\parser.py", line 380, in process_db
  File "forensicsim\backend.py", line 157, in parse_db
  File "ccl_chromium_reader\ccl_chromium_indexeddb.py", line 821, in iterate_records
  File "forensicsim\backend.py", line 75, in custom_iterate_records
TypeError: IndexedDbRecord.__init__() missing 1 required positional argument: 'origin_file'
[5736] Failed to execute script 'main' due to unhandled exception!

**Comment by lxndrblz** [comment]
Did you make sure to try the latest release?
