### ISSUE TITLE
Unhandled exception was occured. ValueError: invalid literal for int() with base 10: 

### ISSUE THREAD

**Issue by kenichi-kobayashi** [lxndrblz/forensicsim#93]
The following error occurred.
Can you tell me what is causing it?

Traceback (most recent call last):
  File "main.py", line 65, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "main.py", line 61, in process_cmd
  File "forensicsim\parser.py", line 381, in process_db
  File "forensicsim\parser.py", line 362, in parse_records
  File "forensicsim\parser.py", line 320, in _parse_reply_chains
  File "dataclasses_json\api.py", line 70, in from_dict
  File "dataclasses_json\core.py", line 219, in _decode_dataclass
  File "forensicsim\parser.py", line 51, in decode_timestamp
ValueError: invalid literal for int() with base 10: '2024-07-19T04:53:15.912Z'
[30212] Failed to execute script 'main' due to unhandled exception!

**Comment by trinamic-mj** [comment]
I suddenly  have the same error. Two days ago it was still working. The log file has not been changed.

  File "main.py", line 65, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "main.py", line 61, in process_cmd
  File "forensicsim\parser.py", line 381, in process_db
  File "forensicsim\parser.py", line 362, in parse_records
  File "forensicsim\parser.py", line 320, in _parse_reply_chains
  File "dataclasses_json\api.py", line 70, in from_dict
  File "dataclasses_json\core.py", line 219, in _decode_dataclass
  File "forensicsim\parser.py", line 51, in decode_timestamp
ValueError: invalid literal for int() with base 10: '2024-08-27T11:32:02.126Z'
[25168] Failed to execute script 'main' due to unhandled exception!

**Comment by trinamic-mj** [comment]
Just found a workaround:
1. close Teams
2. delete all log file
3. restart Teams with refreshed log

**Comment by trinamic-mj** [comment]
Now I get this error:
Traceback (most recent call last):
  File "main.py", line 65, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "main.py", line 61, in process_cmd
  File "forensicsim\parser.py", line 372, in process_db
  File "forensicsim\backend.py", line 75, in parse_db
  File "chromedb\ccl_chromium_indexeddb.py", line 797, in iterate_records
  File "chromedb\ccl_chromium_indexeddb.py", line 600, in iterate_records
  File "chromedb\ccl_v8_value_deserializer.py", line 281, in __init__
  File "chromedb\ccl_v8_value_deserializer.py", line 622, in _read_header
**ValueError: Didn't get version tag in the header**
[26644] Failed to execute script 'main' due to unhandled exception!
