### ISSUE TITLE
ValueError 'version tag in the header'

### ISSUE THREAD

**Issue by trinamic-mj** [lxndrblz/forensicsim#94]
Now I get this error:
Traceback (most recent call last):
  File "main.py", line 65, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "main.py", line 61, in process_cmd
  File "forensicsim\parser.py", line 372, in process_db
  File "forensicsim\backend.py", line 75, in parse_db
  File "chromedb\ccl_chromium_indexeddb.py", line 797, in iterate_records
  File "chromedb\ccl_chromium_indexeddb.py", line 600, in iterate_records
  File "chromedb\ccl_v8_value_deserializer.py", line 281, in __init__
  File "chromedb\ccl_v8_value_deserializer.py", line 622, in _read_header
**ValueError: Didn't get version tag in the header**
[26644] Failed to execute script 'main' due to unhandled exception!

_Originally posted by @trinamic-mj in https://github.com/lxndrblz/forensicsim/issues/93#issuecomment-2376129898_

**Comment by Beercow** [comment]
+1 here as well.
